### ISSUE TITLE
Crash on a specific domain

### ISSUE THREAD

**Issue by danvy** [codex-team/action-check-domain#6]
Hello,
I get a crash using a domain with a .to extension like https://aoz.to
Here is the callstack
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.parseWhoIsData (/home/runner/work/_actions/codex-team/action-check-domain/v1/dist/index.js:1:10361)
    at /home/runner/work/_actions/codex-team/action-check-domain/v1/dist/index.js:1:70054
    at /home/runner/work/_actions/codex-team/action-check-domain/v1/dist/index.js:1:57990
    at Socket.<anonymous> (/home/runner/work/_actions/codex-team/action-check-domain/v1/dist/index.js:1:68499)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:[12](https://github.com/danvy/altoviz-ops/actions/runs/8089117845/job/22104465687#step:2:13)2:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by lissy93** [comment]
I'm seeing this issue to, also on a `.to` domain (https://dashy.to) (workflow run logs [here](https://github.com/Lissy93/dashy/actions/runs/8126828428/job/22211008902))

Seems WHOIS data is returned in a different format for some TLDs (like `.to`). This action uses [`node-whois`](https://github.com/FurqanSoftware/node-whois) which has had a similar issue raised on it (re: [FurqanSoftware/node-whois#114](https://github.com/FurqanSoftware/node-whois/issues/114)).
Actually, when I tried a WHOIS lookup, using [my own whois lookup tool](https://who-dat.as93.net/), and I'm also not able to get parsable data back, for either your .to domain, or my .to domain. Even whois.com [fails](https://www.whois.com/whois/dashy.to) to get full info


This ticket should probably be closed, and a new issue opened upstream on https://github.com/FurqanSoftware/node-whois package. Alternatively, submitting a PR here to switch the NPM package this action uses, to one which is able to handle .to domains (but I don't know of any)
